Controller should add new objects to templateModel
In Groovy context, contentModel is a SiteItem. Statement "contentModel.events = events" will cause this exception:

    groovy.lang.MissingPropertyException: No such property: events for class: org.craftercms.engine.model.DefaultSiteItem